apiVersion: batch/v1
kind: CronJob
metadata:
  name: taxi-rides-outlier-detection-cronjob
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: taxi-rides-outlier-detection
            image: taxi-rides-outlier-detection
            imagePullPolicy: IfNotPresent
            command: ["detect-taxi-ride-outliers", "/data", "2025-01-01"]
            volumeMounts:
            - name: local-folder
              mountPath: /data
          volumes:
          - name: local-folder
            hostPath:
              path: /run/desktop/mnt/host/c/Users/jojog/Documents/School/Semester_2/DEVIL2/ML_OPS/dev2-taxi-rides/work
              type: Directory
          restartPolicy: Never
