apiVersion: batch/v1
kind: CronJob
metadata:
  name: taxi-rides-data-drift-detection-cronjob
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: taxi-rides-data-drift-detection-cronjob
            image: taxi-rides-outlier-detection
            imagePullPolicy: IfNotPresent
            command: ["detect-input-data-drift", "/data"]
            volumeMounts:
            - name: local-folder
              mountPath: /data
          volumes:
          - name: local-folder
            hostPath:
              path: run/desktop/mnt/host/c/Users/jojog/Documents/School/Semester_2/DEVIL2/ML_OPS/dev2-taxi-rides/work
              type: Directory
          restartPolicy: Never
