apiVersion: batch/v1
kind: Job
metadata:
  name: taxi-rides-outlier-detection-job
  namespace: default
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
      - name: taxi-rides-outlier-detection
        image: ghcr.io/jonas-gstoettenmayr/taxi-rides-outlier-detection:1.02
        imagePullPolicy: IfNotPresent
        command: ["detect-taxi-ride-outliers", "/data", "2025-01-01"]
        volumeMounts:
        - name: local-folder
          mountPath: /data
      volumes:
      - name: local-folder
        hostPath:
          path: /run/desktop/mnt/host/c/Users/jojog/Documents/School/Semester_2/DEVIL2/ML_OPS/dev2-taxi-rides/work
          type: Directory
      restartPolicy: OnFailure
